### ISSUE TITLE
NPE: EntityVehicleBase.fixRiderPosOnDismount

### ISSUE THREAD

**Issue by anatawa12** [fixrtm/fixRTM#140]
```
java.lang.NullPointerException: Ticking entity
	at jp.ngt.rtm.entity.vehicle.EntityVehicleBase.fixRiderPosOnDismount(EntityVehicleBase.java:380)
	at jp.ngt.rtm.entity.vehicle.EntityVehicleBase.removePassengerFromVehicle(EntityVehicleBase.java:352)
	at jp.ngt.rtm.entity.vehicle.EntityVehicleBase.func_184225_p(EntityVehicleBase.java:347)
	at net.minecraft.entity.Entity.func_184210_p(Entity.java:2342)
	at net.minecraft.entity.EntityLivingBase.func_184210_p(EntityLivingBase.java:2763)
	at net.minecraft.entity.player.EntityPlayer.func_184210_p(EntityPlayer.java:1325)
	at net.minecraft.entity.player.EntityPlayerMP.func_184210_p(EntityPlayerMP.java:982)
	at net.minecraft.entity.player.EntityPlayer.func_70098_U(EntityPlayer.java:470)
	at net.minecraft.world.World.func_72866_a(World.java:2416)
	at net.minecraft.world.World.func_72870_g(World.java:2372)
	at net.minecraft.world.World.func_72866_a(World.java:2482)
	at net.minecraft.world.World.func_72870_g(World.java:2372)
	at net.minecraft.world.World.func_72939_s(World.java:2142)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:744)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:903)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
	at java.lang.Thread.run(Thread.java:748)
```

[crash-2021-02-22_20.29.00-server.txt](https://github.com/fixrtm/fixRTM/files/6032765/crash-2021-02-22_20.29.00-server.txt)

**Comment by anatawa12** [comment]
set.getCollisionObj().getSizeBox() may returns null on server.
