### ISSUE TITLE
NoClassDefFoundError: Could not initialize class com.creativemd.littletiles.common.tile.math.box.slice.LittleSlice

### ISSUE THREAD

**Issue by anatawa12** [fixrtm/fixRTM#194]
May related by #164 

[crash-2021-03-31_23.40.51-client.txt](https://github.com/fixrtm/fixRTM/files/6271039/crash-2021-03-31_23.40.51-client.txt)

```
java.lang.NoClassDefFoundError: Could not initialize class com.creativemd.littletiles.common.tile.math.box.slice.LittleSlice
	at com.creativemd.littletiles.common.util.shape.DragShapeSliced.getBoxes(DragShapeSliced.java:28)
	at com.creativemd.littletiles.common.item.ItemLittleChisel.getLittlePreview(ItemLittleChisel.java:255)
	at com.creativemd.littletiles.common.item.ItemLittleChisel.getLittlePreview(ItemLittleChisel.java:78)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onRightInteractClient(LittleEventHandler.java:347)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onInteract(LittleEventHandler.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_LittleEventHandler_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

[latest.log](https://github.com/fixrtm/fixRTM/files/6271045/latest.log)

```
java.lang.VerifyError: (class: javax/vecmath/Tuple3d, method: scaleAdd signature: (DLjavax/vecmath/Tuple3f;)V) Incompatible argument to function
	at com.creativemd.creativecore.common.utils.math.Rotation.<init>(Rotation.java:92) ~[Rotation.class:?]
	at com.creativemd.creativecore.common.utils.math.Rotation.<init>(Rotation.java:11) ~[Rotation.class:?]
	at com.creativemd.creativecore.common.utils.math.Rotation$1.<init>(Rotation.java:13) ~[Rotation$1.class:?]
	at com.creativemd.creativecore.common.utils.math.Rotation.<clinit>(Rotation.java:13) ~[Rotation.class:?]
	at com.creativemd.littletiles.common.tile.math.box.slice.LittleSlice.<init>(LittleSlice.java:130) ~[LittleSlice.class:?]
	at com.creativemd.littletiles.common.tile.math.box.slice.LittleSlice.<clinit>(LittleSlice.java:23) ~[LittleSlice.class:?]
	at com.creativemd.littletiles.common.util.shape.DragShapeSliced.getBoxes(DragShapeSliced.java:28) ~[DragShapeSliced.class:?]
	at com.creativemd.littletiles.common.item.ItemLittleChisel.getLittlePreview(ItemLittleChisel.java:255) ~[ItemLittleChisel.class:?]
	at com.creativemd.littletiles.common.item.ItemLittleChisel.getLittlePreview(ItemLittleChisel.java:78) ~[ItemLittleChisel.class:?]
	at com.creativemd.littletiles.common.util.place.PlacementHelper.getPreviews(PlacementHelper.java:184) ~[PlacementHelper.class:?]
	at com.creativemd.littletiles.client.render.overlay.PreviewRenderer.tick(PreviewRenderer.java:119) ~[PreviewRenderer.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_189_PreviewRenderer_tick_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1959) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by anatawa12** [comment]
Closed by #195
