### ISSUE TITLE
java.lang.VerifyError: (class: javax/vecmath/Tuple3d, method: scaleAdd signature: (DLjavax/vecmath/Tuple3f;)V) Incompatible argument to function

### ISSUE THREAD

**Issue by anatawa12** [fixrtm/fixRTM#195]
Relates #194 

Tested with [anatawa12/command-classloader](//github.com/anatawa12/command-classloader), command `/c:load-class javax.vecmath.Tuple3d`.

```
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: java.lang.VerifyError: (class: javax/vecmath/Tuple3d, method: scaleAdd signature: (DLjavax/vecmath/Tuple3f;)V) Incompatible argument to function
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at java.lang.Class.forName0(Native Method)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at java.lang.Class.forName(Class.java:264)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at com.anatawa12.commandclassloader.CommandBase.execute(CommandBase.java:26)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:126)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:98)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1005)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:981)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:47)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:8)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.util.Util.runTask(Util.java:53)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
[21:01:09] [Server thread/INFO] [STDERR]: [com.anatawa12.commandclassloader.CommandBase:execute:28]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by anatawa12** [comment]
with NGTLib `NGTLib2.4.18-35_forge-1.12.2-14.23.2.2611`, RTM `RTM2.4.21-40_forge-1.12.2-14.23.2.2611`, and command-classloader `command-classloader-1.0`, This error will be happened

**Comment by anatawa12** [comment]
The error shows some invoke instruction in `javax/vecmath/Tuple3d.scaleAdd:(DLjavax/vecmath/Tuple3f;)V` is not vaild https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/a1d853a5d797f38f7be8c260f4a83c1b3fe48adc/jdk/src/share/native/common/check_code.c#L2447

**Comment by anatawa12** [comment]
The error was happened after constructing models, not happened before constructing

**Comment by anatawa12** [comment]
With `scriptingMode=cache-with-sai` and `scriptingMode=better-with-nashorn`, This error was not happened. happens only with `scriptingMode=use-rtm-normal`.
