### ISSUE TITLE
Incompatible with Hwyla when place rail

### ISSUE THREAD

**Issue by anatawa12** [fixrtm/fixRTM#222]
By Trollebas

```
: Unexpected error

java.lang.NullPointerException: Unexpected error
	at jp.ngt.rtm.item.ItemRail.setRPToItem(ItemRail.java:220)
	at jp.ngt.rtm.item.ItemRail.copyItemFromRail(ItemRail.java:231)
	at jp.ngt.rtm.rail.BlockLargeRailBase.getPickBlock(BlockLargeRailBase.java(modified by fixrtm):217)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:140)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:57)
	at mcp.mobius.waila.overlay.DecoratorRenderer.onRenderWorldLast(DecoratorRenderer.java:27)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_DecoratorRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1959)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

[error_crash_rail.zip](https://github.com/fixrtm/fixRTM/files/6643325/error_crash_rail.zip)

**Comment by anatawa12** [comment]
It looks caused by Hwyla, It looks a rail block was picked before finish constructing BockLargeRail

**Comment by anatawa12** [comment]
Still Crashing: 
```
java.lang.NullPointerException: null
	at jp.ngt.rtm.rail.TileEntityLargeRailNormalCore.getRailShapeName(TileEntityLargeRailNormalCore.java:13) ~[TileEntityLargeRailNormalCore.class:?]
	at jp.ngt.rtm.item.ItemRail.copyItemFromRail(ItemRail.java(modified by fixrtm):200) ~[ItemRail.class:?]
	at jp.ngt.rtm.rail.BlockLargeRailBase.getPickBlock(BlockLargeRailBase.java(modified by fixrtm):217) ~[BlockLargeRailBase.class:?]
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:140) ~[RayTracing.class:?]
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73) ~[RayTracing.class:?]
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:57) ~[RayTracing.class:?]
	at mcp.mobius.waila.overlay.DecoratorRenderer.onRenderWorldLast(DecoratorRenderer.java:27) ~[DecoratorRenderer.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_50_DecoratorRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196) ~[ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669) ~[Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1959) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by anatawa12** [comment]
https://discord.com/channels/749186892733480970/749187907033497601/863481883895660587
