### ISSUE TITLE
NPE Tried to use the horn on a train

### ISSUE THREAD

**Issue by anatawa12** [fixrtm/fixRTM#285]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

[from discord user @436238756853579776](https://discord.com/channels/749186892733480970/749187907033497601/876494947489021952)

crash when Tried to use the horn on a train
pretty sure I have all sounds depencies libraries installed

[crash-2021-08-15_17.54.40-client.txt](https://github.com/fixrtm/fixRTM/files/6989532/crash-2021-08-15_17.54.40-client.txt)

```
java.lang.NullPointerException: Unexpected error
	at jp.ngt.rtm.event.RTMKeyHandlerClient.playSound(RTMKeyHandlerClient.java(modified by fixrtm):155)
	at jp.ngt.rtm.event.RTMKeyHandlerClient.keyDown(RTMKeyHandlerClient.java(modified by fixrtm):88)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_RTMKeyHandlerClient_keyDown_InputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:565)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2017)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

### To Reproduce

Tried to use the horn on a train

Pack is this one (https://yuzuhortm.wixsite.com/yuzuho/post/hosenkit)

### OS

N/A

### Minecraft Forge Version

2854

### fixRTM Version

2.0.19

**Comment by anatawa12** [comment]
reproduced
