### ISSUE TITLE
Crash when entering server

### ISSUE THREAD

**Issue by anatawa12** [fixrtm/fixRTM#288]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

Crash 
[crash-2021-08-21_15.32.26-client.txt](https://github.com/fixrtm/fixRTM/files/7025593/crash-2021-08-21_15.32.26-client.txt)

### To Reproduce

N/A

### OS

Windows 10 (amd64) version 10.0

### Minecraft Forge Version

14.23.5.2821

### fixRTM Version

SNAPSHOT-2021-08-15-06-27-14

**Comment by anatawa12** [comment]
StackTrace: 
```
java.lang.NullPointerException: Rendering Block Entity
	at jp.ngt.rtm.block.tileentity.RenderOrnament.renderOrnament(RenderOrnament.java:26)
	at jp.ngt.rtm.block.tileentity.RenderOrnament.render(RenderOrnament.java:39)
	at jp.ngt.rtm.block.tileentity.RenderOrnament.func_192841_a(RenderOrnament.java:13)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:201)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:157)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1032)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by anatawa12** [comment]
ModelPackManager#unconstructSets  looks not synced and not concurrent. it may be problem
