### ISSUE TITLE
ERROR: 0:31: No matching function for call to abs(int)

### ISSUE THREAD

**Issue by anatawa12** [fixrtm/fixRTM#378]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

[crash-2021-11-23_07.49.34-client.txt](https://github.com/fixrtm/fixRTM/files/7701442/crash-2021-11-23_07.49.34-client.txt)

```

java.lang.RuntimeException: ERROR: 0:31: No matching function for call to abs(int)

	at jp.ngt.ngtlib.renderer.GLHelper.createShader(GLHelper.java:316)
	at jp.ngt.ngtlib.renderer.GLHelper.getShaderProgram(GLHelper.java:272)
	at jp.ngt.rtm.gui.camera.Camera.init(Camera.java:115)
	at jp.ngt.rtm.gui.camera.Camera.render(Camera.java:264)
	at jp.ngt.rtm.gui.GuiIngameCustom.onRenderGui(GuiIngameCustom.java:71)
	at jp.ngt.rtm.event.RTMEventHandlerClient.onRenderGui(RTMEventHandlerClient.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_31_RTMEventHandlerClient_onRenderGui_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:135)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.run(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.legacydev.Main.start(Main.java:86)
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)
```

### To Reproduce

Use camera on macos 12.0.1.

### OS

macos 12.0.1

### Minecraft Forge Version

2854 dev

### fixRTM Version

dev 1c7f97c3

**Comment by anatawa12** [comment]
WIP on port-camera-to-macos
