### ISSUE TITLE
NPE at ForgeHooks.onPickBlock when we pick a rail

### ISSUE THREAD

**Issue by anatawa12** [fixrtm/fixRTM#90]
```
java.lang.NullPointerException: Unexpected error
	at net.minecraftforge.common.ForgeHooks.onPickBlock(ForgeHooks.java:532)
	at net.minecraft.client.Minecraft.func_147112_ai(Minecraft.java:2604)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2259)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
```

[crash-2020-05-27_17.57.30-client.txt](https://github.com/anatawa12/fixRTM/files/4688941/crash-2020-05-27_17.57.30-client.txt)

**Comment by anatawa12** [comment]
BlockLargeRailBase sometimes returns null
